### ISSUE TITLE
Configuring Node-RED on a Vagrant VM using Ansible

### ISSUE THREAD

**Issue by tappoz** [node-red/node-red#2019]
### What are the steps to reproduce?

I am configuring a Vagrant Virtual Machine running Debian Jessie with Ansible as the provisioner.

I would like to install, configure and run Node-RED as a Systemd service, using NVM (Node Version Manager: https://github.com/creationix/nvm).

I've executed the following Ansible YAML script (no errors). This has been inspired by the docs here https://nodered.org/docs/getting-started/installation (e.g. the `npm` flag `--unsafe-perm` which I don't completely understand why it has to be used as I don't understand the official `npm` docs about that flag, also specifying the exact version for Node-RED with `node-red@{{ nodered_version }}`):

```yaml
  - name: Install Node-RED
    shell: export NVM_DIR="/home/{{ user_name }}/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && /home/{{ user_name }}/.nvm/versions/node/v{{ node_version }}/bin/npm install -g --unsafe-perm node-red@{{ nodered_version }}
    args:
      executable: /bin/bash
      creates: /home/{{ user_name }}/.nvm/versions/node/v{{ node_version }}/lib/node_modules/node-red/package.json
  - name: Copy node-red system configuration files
    copy:
      src: "{{ item.0 }}"
      dest: "{{ item.1 }}"
      owner: root
      group: root
      mode: "{{ item.2 }}"
    with_together:
      - [ './data_dir/node-red-start', './data_dir/node-red-stop' ]
      - [ '/usr/bin/node-red-start',   '/usr/bin/node-red-stop'   ]
      - [ '0755',                      '0755'                     ]
  - name: Copy and configure the Systemctl service
    template:
      src: ./data_dir/nodered.service.j2
      dest: /lib/systemd/system/nodered.service
      mode: 0644
    # sudo systemctl enable nodered.service
  - name: Enable the systemd service for Node-RED
    systemd:
      name: nodered
      state: started
      enabled: yes
```

The `node-red-start` and `node-red-stop` files have been previously downloaded and made available to Ansible with the following command (is there an alternative place where these could be downloaded as linked to a Node-RED version/release?):

```sh
wget https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/node-red-start
wget https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/node-red-stop
```

The Node-RED Systemd configuration file has been downloaded in a similar way with `wget`, then modified as a Jinja template that Ansible can parse and injected at runtime with variables replacements (see below). 

I've taken this doc https://nodered.org/docs/hardware/raspberrypi#adding-autostart-capability-using-systemd as the reference, however I am not sure why a Raspberry Pi running Raspbian should be different than a Vagrant VM running Debian Jessie.

As can be seen below this file has to be tweaked a bit in order to run the `nvm` command and `node` version in the user at `/home/vagrant` pretending to be `sudo` (so I have to use a prefix to set the `nvm` environment which lives in a different user home directory).

The Jinja template for the Systemd service configuration file eventually placed in `/lib/systemd/system/nodered.service`:

```
# systemd service file to start Node-RED

[Unit]
Description=Node-RED graphical event wiring tool
Wants=network.target
Documentation=http://nodered.org/docs/hardware/raspberrypi.html

[Service]
Type=simple
# Run as normal pi user - change to the user name you wish to run Node-RED as
User={{ user_name }}
Group={{ user_name }}
WorkingDirectory=/home/{{ user_name }}

Nice=5
Environment="NODE_OPTIONS=--max_old_space_size=256"
# uncomment and edit next line if you need an http proxy
#Environment="HTTP_PROXY=my.httpproxy.server.address"
# uncomment the next line for a more verbose log output
Environment="NODE_RED_OPTIONS=-v"
#ExecStart=/usr/bin/env node $NODE_OPTIONS red.js $NODE_RED_OPTIONS
ExecStart=/bin/sh /home/{{ user_name }}/.nvm/nvm.sh && /home/{{ user_name }}/.nvm/versions/node/v{{ node_version }}/bin/node-red-pi $NODE_OPTIONS $NODE_RED_OPTIONS
# Use SIGINT to stop
KillSignal=SIGINT
# Auto restart on crash
Restart=on-failure
# Tag things in the log
SyslogIdentifier=Node-RED
#StandardOutput=syslog

[Install]
WantedBy=multi-user.target
```

### What happens?

I keep visiting the web page `<VM_IP>:1880`, but the Node-RED web interface is not available.

Looking at the Systemctl logs it seems it worked:

```sh
$ sudo journalctl -f -u nodered 
-- Logs begin at Sat 2018-12-22 12:27:50 GMT. --
Dec 26 15:40:58 jessie systemd[1]: Starting Node-RED graphical event wiring tool...
Dec 26 15:40:58 jessie systemd[1]: nodered.service start request repeated too quickly, refusing to start.
Dec 26 15:40:58 jessie systemd[1]: Failed to start Node-RED graphical event wiring tool.
Dec 26 15:40:58 jessie systemd[1]: Unit nodered.service entered failed state.
Dec 26 15:44:52 jessie systemd[1]: Starting Node-RED graphical event wiring tool...
Dec 26 15:44:52 jessie systemd[1]: Started Node-RED graphical event wiring tool.
Dec 26 15:48:58 jessie systemd[1]: Starting Node-RED graphical event wiring tool...
Dec 26 15:48:58 jessie systemd[1]: Started Node-RED graphical event wiring tool.
Dec 26 15:51:32 jessie systemd[1]: Starting Node-RED graphical event wiring tool...
Dec 26 15:51:32 jessie systemd[1]: Started Node-RED graphical event wiring tool.
```

However when checking the status of the service it seems dead:

```sh
$ systemctl status nodered.service
● nodered.service - Node-RED graphical event wiring tool
   Loaded: loaded (/lib/systemd/system/nodered.service; enabled)
   Active: inactive (dead) since Wed 2018-12-26 15:51:32 GMT; 17min ago
     Docs: http://nodered.org/docs/hardware/raspberrypi.html
  Process: 15599 ExecStart=/bin/sh /home/vagrant/.nvm/nvm.sh && /home/vagrant/.nvm/versions/node/v10.14.2/bin/node-red-pi $NODE_OPTIONS $NODE_RED_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 15599 (code=exited, status=0/SUCCESS)

Warning: Unit file changed on disk, 'systemctl daemon-reload' recommended.
```

I've already tried to run `systemctl daemon-reload` but it looks that disappearing warning has not an effect on Node-RED. 

### What do you expect to happen?

I expect to be able to access the Node-RED UI via web pointing to a properly configured running instance of Node-RED.

I know this is working because I can see the web UI when running the commands (what's the difference?):

- `node-red`
- `node-red-start`

### Please tell us about your environment:

- [ ] Node-RED version: 0.19.5
- [ ] node.js version: 10.14.2
- [ ] npm version: 6.4.1
- [ ] Platform/OS: Linux Debian Jessie 8.11
- [ ] Browser: any (even `wget`), but anyway: Chromium 71.0.3578.80
