### ISSUE TITLE
@node-red/editor-client	Css overrides global styles for HTML elements

### ISSUE THREAD

**Issue by KamalAman** [node-red/node-red#2110]
### What are the steps to reproduce?
@node-red/editor-client defines global css styles that effect all DOM elements

### What happens?
@node-red/editor-client defines global overrides for css styles because it uses styles extracted from Bootstrap v2.3.2.

For example all textareas get the following style applied to them:
```css
textarea,input[type="text"],input[type="password"],input[type="datetime"],input[type="datetime-local"],input[type="date"],input[type="month"],input[type="time"],input[type="week"],input[type="number"],input[type="email"],input[type="url"],input[type="search"],input[type="tel"],input[type="color"],div[contenteditable="true"],.uneditable-input {
    background-color: #ffffff;
    border: 1px solid #ccc;
    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,0.075);
    -moz-box-shadow: inset 0 1px 1px rgba(0,0,0,0.075);
    box-shadow: inset 0 1px 1px rgba(0,0,0,0.075)
}
```

This results in unwanted styling being applied. For example if you wanted to use a UI component libraries such as material-ui or define your own custom component, you need to apply ani-styles to counteract these styles.

### What do you expect to happen?
No global element styles should be defined for HTML elements. Specify at least 1 class name or class name descendant for styles e.g.  `.form-row > textarea` 

The following is the list of styles that should be made more restrictive 
```css
button,input,select,div[contenteditable="true"],textarea
button,div[contenteditable="true"],input
button::-moz-focus-inner,div[contenteditable="true"]::-moz-focus-inner,input::-moz-focus-inner
button,html input[type="button"],input[type="reset"],input[type="submit"]
label,select,button,input[type="button"],input[type="reset"],input[type="submit"],input[type="radio"],input[type="checkbox"]
input[type="search"]
input[type="search"]::-webkit-search-decoration,input[type="search"]::-webkit-search-cancel-button
textarea
form
fieldset
legend
legend small
label,input,div[contenteditable="true"],button,select,textarea
input,div[contenteditable="true"],button,select,textarea
label 
select,textarea,input[type="text"],input[type="password"],input[type="datetime"],input[type="datetime-local"],input[type="date"],input[type="month"],input[type="time"],input[type="week"],input[type="number"],input[type="email"],input[type="url"],input[type="search"],input[type="tel"],input[type="color"],div[contenteditable="true"],.uneditable-input
input,textarea,div[contenteditable="true"],.uneditable-input
textarea 
textarea,input[type="text"],input[type="password"],input[type="datetime"],input[type="datetime-local"],input[type="date"],input[type="month"],input[type="time"],input[type="week"],input[type="number"],input[type="email"],input[type="url"],input[type="search"],input[type="tel"],input[type="color"],div[contenteditable="true"],.uneditable-input 
textarea:focus,input[type="text"]:focus,input[type="password"]:focus,input[type="datetime"]:focus,input[type="datetime-local"]:focus,input[type="date"]:focus,input[type="month"]:focus,input[type="time"]:focus,input[type="week"]:focus,input[type="number"]:focus,input[type="email"]:focus,input[type="url"]:focus,input[type="search"]:focus,input[type="tel"]:focus,input[type="color"]:focus,div[contenteditable="true"]:focus,.uneditable-input:focus
input[type="radio"],input[type="checkbox"]
input[type="file"],input[type="image"],input[type="submit"],input[type="reset"],input[type="button"],input[type="radio"],input[type="checkbox"] 
select,input[type="file"] 
select 
select[multiple],select[size] 
select:focus,input[type="file"]:focus,input[type="radio"]:focus,input[type="checkbox"]:focus
```

### Please tell us about your environment:

- [ ] Node-RED version: 0.20.3
- [ ] node.js version: 10.10
- [ ] npm version: 6.4.1
- [ ] Platform/OS: macOX
- [ ] Browser: Chrome
