### ISSUE TITLE
how to setting Timezone in docker swarm

### ISSUE THREAD

**Issue by kervin521** [node-red/node-red#2393]
### What are the steps to reproduce?
```yml
version: '3.7'
services:
   node-red-04:
      image: 172.21.32.102:5000/nodered/node-red:1.0.3
      restart: always
      privileged: true
      environment:
      - TZ=Asia/Shanghai
      - process.env.TZ=Asia/Shanghai
      volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      ports:
      - 18804:1880
      deploy:
         replicas: 1
```

### What happens?
![image](https://user-images.githubusercontent.com/9798724/69536340-c6af5580-0fb8-11ea-80df-d60812eed33d.png)

### Please tell us about your environment:

- [ ] Node-RED version:
- [ ] Node.js version:
- [ ] npm version:
- [ ] Platform/OS:
- [ ] Browser:
