### ISSUE TITLE
Quick add list recent used hidden since addition of new nodes (v3)

### ISSUE THREAD

**Issue by Steve-Mcl** [node-red/node-red#3568]
### Current Behavior

The quick add list used to show 1 (or more - i forget) but since new "priority" items have been added, the recently used list is not visible

![image](https://user-images.githubusercontent.com/44235289/166219276-184e36ee-ffaf-48e9-8b18-322867b35d6f.png)

### Expected Behavior

Would be nice to see more items in the recently used list - perhaps 5 items?

![image](https://user-images.githubusercontent.com/44235289/166219251-6683f336-b7d0-4d12-8342-4de5d658804b.png)

NOTE: this example ↑ was faked by tweaking `height` to 222 
```css
.red-ui-type-search .red-ui-search-results-container {
    display: none;
    height: 222px;
}
```

### Steps To Reproduce

Open quick add list for NR v3 beta

### Example flow

NA

### Environment

- Node-RED version: 3 beta 1
- Node.js version: 16
- npm version:
- Platform/OS:
- Browser: All
