### ISSUE TITLE
Crash with Client network socket disconnected error

### ISSUE THREAD

**Issue by winnieXY** [node-red/node-red#3903]
### Current Behavior

I'm running node-red dockerized in docker swarm using this compose snipplet ( so nodered/node-red:latest):

```
  nodered:
    image: nodered/node-red
    container_name: nodered
    hostname: nodered
    user: "1000:1000"
    restart: always
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /home/docker/nodered/data:/data
    links:
      - influxdb
      - mosquitto
    ports:
      - 1880:1880
      - 2048:2048
      - 2049:2049
    labels:
       - swarmpit.service.deployment.autoredeploy=true
    deploy:
      placement:
        constraints:
        - node.role == manager
      resources:
        limits:
          cpus: '3'
          memory: 800M
        reservations:
          cpus: '1'
          memory: 300M
```

Sometimes node-red crashes right after the start with this error message:

```
 28 Sep 15:31:30 - [red] Uncaught Exception:
 28 Sep 15:31:30 - [error] Error: Client network socket disconnected before secure TLS connection was established
     at connResetException (node:internal/errors:692:14)
     at TLSSocket.onConnectEnd (node:_tls_wrap:1587:19)
     at TLSSocket.emit (node:events:539:35)
     at endReadableNT (node:internal/streams/readable:1345:12)
     at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

This happens almost always when I want to start up the stack. Usually the second task is successfull and don't crash.

### Expected Behavior

No crash when starting up the stack. This was the case with Node-Red 2.x - this behaviour started with node-red 3.x. 

### Steps To Reproduce

not sure

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: latest docker tag
- Node.js version: see docker image
- npm version: see docker image
- Platform/OS: docker
- Browser: firefox
