### ISSUE TITLE
Node-red is asking for passphrase in git push even after not configured for it after restart

### ISSUE THREAD

**Issue by RohitashavSoni** [node-red/node-red#4618]
### Current Behavior

Before restart : 

Created the SSH key for GitHub pull and push and it's working fine.

After restart : 

When ever we are trying to push the data, its asking for passphrase as shown in the picture 
![image](https://github.com/node-red/node-red/assets/86046518/bb4ac902-ec5b-4983-b63a-6f2a2f841083)

my setting.js is like this 
![image](https://github.com/node-red/node-red/assets/86046518/5f416206-6c51-4caa-96e2-8f9208501cf6)

I am not sure what's the problem. I think maybe I need to make some changes in setting.js.

### Expected Behavior

After restart, user should be able to push to GitHub form node-red without asking for passphrase if not configured, 

### Steps To Reproduce

1. Freshly install NODE-RED using this command : 'sudo npm install -g --unsafe-perm node-red'
2. Enable  and the project form setting.js.
3. Create a SSH key and map it GitHub, push some thing
4. Restart the nodered 

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.1.7
- Node.js version: v18.13.0
- npm version: 9.2.0
- Platform/OS: Debian 12
- Browser: FireFox

**Comment by dmunozv04** [comment]
I can confirm it's not a one-off, I've been able to replicate it

**Comment by dmunozv04** [comment]
It seems to be related with checking if a `key_path` has been saved, which isn't set on startup. https://github.com/node-red/node-red/blob/master/packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/git/index.js#L451

**Comment by lucboj** [comment]
I can also confirm this problem. It has now happened on multiple Node-RED instances. It happens with or without setting a passphrase and it always occurs after a restart. The problem has been observed on the versions 3.1.3 and 4.0.5.

After looking a little more in to it, I think I have found the issue. It seems that after restarting Node-RED the SSH key files get their permission changed. Example:

Permissions before restart:

```
$ ls -l
total 8
-rw-------    1 node-red node-red      3434 Dec 16 09:08 admin_new-key
-rw-r--r--    1 node-red node-red       753 Dec 16 09:08 admin_new-key.pub
```

Permissions after restart:

```
$ ls -l
total 8
-rw-rw----    1 node-red node-red      3434 Dec 16 09:08 admin_new-key
-rw-rw-r--    1 node-red node-red       753 Dec 16 09:08 admin_new-key.pub
```

When checking the SSH key against GitHub the following error occurs:

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0660 for 'admin_new-key' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "admin_new-key": bad permissions
git@github.com: Permission denied (publickey).
```

If using Node-RED in Kubernetes the workaround is to deploy the pod with an initContainer with a script which changes the permissions for the SSH key files: 

```yaml
    initContainers:
    - name: fix-ssh-permissions
      image: node
      command: ["/bin/sh", "-c"]
      args:
        - |
          set -e
          # Fix permissions for private and public keys
          for key in /data/projects/.sshkeys/*; do
            if [ -f "$key" ]; then
              if echo "$key" | grep -qE "\.pub$"; then
                chmod 644 "$key"
                echo "Set permissions to 644 for public key: $key"
              else
                chmod 600 "$key"
                echo "Set permissions to 600 for private key: $key"
              fi
            fi
          done
          echo "Permissions update completed."
      volumeMounts:
      - name: node-red-data
        mountPath: /data
```

**Comment by hardillb** [comment]
@lucboj are you using the standard `nodered/node-red docker` container for your kube pod?

What are you using as the storage class for your volume mounted on `/data`?

There should be nothing in the container (or in NR, but double checking) that should be changing the permissions on start up, so I'm trying to work out what could be modifying the permissions.

**Comment by suxxez** [comment]
@hardillb I'm working with @lucboj and we've experienced this problem on two separate Managed K8s platforms, which are using different custom storage classes, as well as on a MicroK8s cluster with `openebs-hostpath` storage class. So it seems to be independent of the storage class. Using the standard `nodered/node-red:4.0.5` image. 

The fix is working great, the cause would be interesting to know nonetheless :)

**Comment by hardillb** [comment]
Please provide the yaml dirt the pod/deployment

**Comment by suxxez** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nr-test
  namespace: default
  labels:
    app: nr-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "nr-test"
  template:
    metadata:
      labels:
        app: nr-test
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: nr-test
        image: nodered/node-red:4.0.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1880
        volumeMounts:
          - name: settings
            mountPath: /data/settings.js
            subPath: settings.js
          - name: node-red-data
            mountPath: /data
      initContainers:
      - name: predeploy-task
        image: node
        command: [ "npm", "install", "--prefix", "/data", "passport-keycloak-oauth2-oidc" ]
        volumeMounts:
        - name: node-red-data
          mountPath: /data
      volumes:
        - name: settings
          configMap:
            name: nr-test-settings-js
            items:
            - key: settings.js
              path: settings.js
        - name: node-red-data
          persistentVolumeClaim:
            claimName: nr-test-claim
  hooks:
    pre:
    - name: predeploy-hook
      type: Job
      podTemplate:
        spec:
          containers:
            - name: predeploy-container
              image: node
              command: [ "predeploy-task" ]
          restartPolicy: Never
      jobTargetRef:
        apiVersion: batch/v1
        kind: Job
        name: predeploy-job
```

**Comment by hardillb** [comment]
Thanks,

Can I get the PVC as well please and just to double check, waht is the predeploy-hook doing?

I have a k3s node I can give this a try with a localfs volume and a microk8s cluster withe NFS volumes I'll try as well when I get some time.

**Comment by suxxez** [comment]
Thanks, much appreciated!

The predeploy hook just confirms that the initContainer (which installs an npm package) has run successfully before starting Node-RED.

Here's the PVC:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nr-test-claim
  namespace: default
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
```

And, just to double-check myself: I've spotted this line in the Dockerfile which changes permissions of `/data` directory.

https://github.com/node-red/node-red-docker/blob/master/docker-custom/Dockerfile.custom#L27

But this shouldn't impact the startup of the container, as it is just run when the image is built, right?
